import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header"
import Footer from "./components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Header/>
          <div className="min-h-screen bg-linear-to-b from-gray-900 via-gray-800 to-black text-white">
          {children}
          </div>
          <Footer/>
      </body>
    </html>
  );
}

